import type { Metadata } from 'next';
import './globals.css';
import { vt2323 } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={vt2323.className}>{children}</body>
    </html>
  );
}
